#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + H2 <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 1,
    label = "X + N2 <=> N#N.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 2,
    label = "X + X + H2 <=> [Pt] + [Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 3,
    label = "H + H <=> H2",
    degeneracy = 0.5,
    duplicate = True,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 4,
    label = "X + H <=> [Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 5,
    label = "H + H <=> H2",
    degeneracy = 0.5,
    duplicate = True,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 6,
    label = "H + NNHJ <=> N2 + H2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(2.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
    This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
family: Disproportionation
""",
)

entry(
    index = 7,
    label = "N2 + H <=> NNHJ",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.6e+15,'cm^3/(mol*s)'), n=-0.64, Ea=(15333,'cal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(25000,'K'), comment="""Matched reaction 185 N2 + H <=> NNH in R_Addition_MultipleBond/training
    This reaction matched rate rule [N3t_N3t;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 185 N2 + H <=> NNH in R_Addition_MultipleBond/training
This reaction matched rate rule [N3t_N3t;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 8,
    label = "H + NNHJ <=> N2 + H2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(2.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
    This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
family: Disproportionation
""",
)

entry(
    index = 9,
    label = "X + NNHJ <=> NNHJX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 10,
    label = "X + NNHJ <=> [Pt]N=N",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 11,
    label = "X + NNHJ <=> NNHJX-2",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(26.4446,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW
    Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 12,
    label = "H + HNNH <=> NNHJ + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(9.6e+08,'cm^3/(mol*s)'), n=1.5, Ea=(6.61072,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 636 H + H2N2 <=> H2 + HN2 in H_Abstraction/training
    This reaction matched rate rule [H2;N3d_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 636 H + H2N2 <=> H2 + HN2 in H_Abstraction/training
This reaction matched rate rule [H2;N3d_rad]
family: H_Abstraction
""",
)

entry(
    index = 13,
    label = "H + NNHJ <=> HNNH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.24474e+12,'m^3/(mol*s)'), n=-1.49865, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.381367412635, var=9.46235787476, Tref=1000.0, N=7, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
        Total Standard Deviation in ln(k): 7.12496428854
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
    Total Standard Deviation in ln(k): 7.12496428854
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 14,
    label = "NNHJ + NNHJ <=> N2 + HNNH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2, Ea=(-4.97896,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [N3d_rad;N3d/H_d_Nrad] for rate rule [N3d_rad/N;N3d/H_d_Nrad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [N3d_rad;N3d/H_d_Nrad] for rate rule [N3d_rad/N;N3d/H_d_Nrad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 15,
    label = "X + X + HNNH <=> [Pt] + [Pt]N=N",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 16,
    label = "X + HNNH <=> N=N.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 17,
    label = "H + NNH2(S) <=> NNHJ + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.8e+08,'cm^3/(mol*s)'), n=1.5, Ea=(17.4054,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 3073 used for N5dc_H;H_rad
    Exact match found for rate rule [N5dc_H;H_rad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 3073 used for N5dc_H;H_rad
Exact match found for rate rule [N5dc_H;H_rad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 18,
    label = "H + NNHJ <=> NNH2(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.24474e+12,'m^3/(mol*s)'), n=-1.49865, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.381367412635, var=9.46235787476, Tref=1000.0, N=7, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
        Total Standard Deviation in ln(k): 7.12496428854
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
    Total Standard Deviation in ln(k): 7.12496428854
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 19,
    label = "NNHJ + NNHJ <=> N2 + NNH2(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.1973,'m^3/(mol*s)'), n=1.93833, Ea=(-4.81857,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;N3d/H_d_Nrad] for rate rule [N5_rad;N3d/H_d_Nrad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;N3d/H_d_Nrad] for rate rule [N5_rad;N3d/H_d_Nrad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 20,
    label = "X + X + NNH2(S) <=> [Pt] + NNHJX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 21,
    label = "NNHJ + NNH2(S) <=> NNHJ + HNNH",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.84e+06,'cm^3/(mol*s)'), n=1.94, Ea=(3.64008,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using template [N5dc_H;N3_rad] for rate rule [N5dc_H;N3d_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [N5dc_H;N3_rad] for rate rule [N5dc_H;N3d_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 22,
    label = "X + NNH2(S) <=> NNH2(S)X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

