#!/usr/bin/env python
# encoding: utf-8

name = "seed_edge"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "H + H2NN(T) <=> NNHJ + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(9.6e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 85 H + H2N2 <=> H2 + HN2 in Disproportionation/training
    This reaction matched rate rule [H_rad;N3s/H2_s_Nbirad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 85 H + H2N2 <=> H2 + HN2 in Disproportionation/training
This reaction matched rate rule [H_rad;N3s/H2_s_Nbirad]
family: Disproportionation
""",
)

entry(
    index = 1,
    label = "H + HNNH <=> NNHJ + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(9.6e+08,'cm^3/(mol*s)'), n=1.5, Ea=(6.61072,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 636 H + H2N2 <=> H2 + HN2 in H_Abstraction/training
    This reaction matched rate rule [H2;N3d_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 636 H + H2N2 <=> H2 + HN2 in H_Abstraction/training
This reaction matched rate rule [H2;N3d_rad]
family: H_Abstraction
""",
)

entry(
    index = 2,
    label = "H + N2H2(T) <=> NNHJ + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.8e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using an average for rate rule [H_rad;NH_s_Rbirad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [H_rad;NH_s_Rbirad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 3,
    label = "H + NNH2(S) <=> NNHJ + H2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.8e+08,'cm^3/(mol*s)'), n=1.5, Ea=(17.4054,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 3073 used for N5dc_H;H_rad
    Exact match found for rate rule [N5dc_H;H_rad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 3073 used for N5dc_H;H_rad
Exact match found for rate rule [N5dc_H;H_rad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 4,
    label = "H + NNHJ <=> HNNH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.24474e+12,'m^3/(mol*s)'), n=-1.49865, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.381367412635, var=9.46235787476, Tref=1000.0, N=7, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
        Total Standard Deviation in ln(k): 7.12496428854
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
    Total Standard Deviation in ln(k): 7.12496428854
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 5,
    label = "H + NNHJ <=> NNH2(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.24474e+12,'m^3/(mol*s)'), n=-1.49865, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.381367412635, var=9.46235787476, Tref=1000.0, N=7, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
        Total Standard Deviation in ln(k): 7.12496428854
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
    Total Standard Deviation in ln(k): 7.12496428854
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 6,
    label = "NNHJ + NNHJ <=> N2 + HNNH",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+06,'cm^3/(mol*s)'), n=2, Ea=(-4.97896,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [N3d_rad;N3d/H_d_Nrad] for rate rule [N3d_rad/N;N3d/H_d_Nrad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [N3d_rad;N3d/H_d_Nrad] for rate rule [N3d_rad/N;N3d/H_d_Nrad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 7,
    label = "NNHJ + NNHJ <=> NDNNDN",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(5.1562e+30,'m^3/(mol*s)'), n=-7.48856, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.354218852058, var=34.8187486739, Tref=1000.0, N=6, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
        Total Standard Deviation in ln(k): 12.7194203157
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
    Total Standard Deviation in ln(k): 12.7194203157
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 8,
    label = "NNHJ + NNHJ <=> N2 + NNH2(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.1973,'m^3/(mol*s)'), n=1.93833, Ea=(-4.81857,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;N3d/H_d_Nrad] for rate rule [N5_rad;N3d/H_d_Nrad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;N3d/H_d_Nrad] for rate rule [N5_rad;N3d/H_d_Nrad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 9,
    label = "X + X + NNH2(S) <=> H_X + NNHJX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 10,
    label = "X + X + HNNH <=> H_X + [Pt]N=N",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 11,
    label = "X + [Pt]NN=N <=> NH_X + [Pt]N=N",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(141.781,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 12,
    label = "X + X + NDNNDN <=> [Pt]N=N + [Pt]N=N",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 13,
    label = "X + NH2(D) <=> NH2_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 14,
    label = "X + NN[Pt] <=> NH_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(155.952,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 15,
    label = "X + X + NH2NHN <=> NNHJX + NH2_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 16,
    label = "X + X + HNNNH2 <=> [Pt]N=N + NH2_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 17,
    label = "X + X + NH2NH2 <=> NH2_X + NH2_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 18,
    label = "H + NH2(D) <=> NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.35832e+07,'m^3/(mol*s)'), n=0.0354724, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.256587721226, var=1.96898110437, Tref=1000.0, N=27, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing
        Total Standard Deviation in ln(k): 3.45774478839
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing
    Total Standard Deviation in ln(k): 3.45774478839
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 19,
    label = "NH2NHN <=> N2 + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.17e+08,'s^-1'), n=3.54, Ea=(48.2,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K'), comment="""Fitted to 51 data points; dA = *|/ 2.36471, dn = +|- 0.107367, dEa = +|- 0.813875 kJ/molMatched reaction 3 NH2NHN_r <=> NH3 + N2 in 1,2_NH3_elimination/training
    This reaction matched rate rule [chargedD]
    family: 1,2_NH3_elimination"""),
    longDesc = 
"""
Fitted to 51 data points; dA = *|/ 2.36471, dn = +|- 0.107367, dEa = +|- 0.813875 kJ/molMatched reaction 3 NH2NHN_r <=> NH3 + N2 in 1,2_NH3_elimination/training
This reaction matched rate rule [chargedD]
family: 1,2_NH3_elimination
""",
)

entry(
    index = 20,
    label = "HNNNH2 <=> N2 + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.9e+09,'s^-1'), n=1.34, Ea=(142.2,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(3000,'K'), comment="""Matched reaction 1 NH2NNH_r <=> NH3 + N2 in 1,3_NH3_elimination/training
    This reaction matched rate rule [NHDNNH2]
    family: 1,3_NH3_elimination"""),
    longDesc = 
"""
Matched reaction 1 NH2NNH_r <=> NH3 + N2 in 1,3_NH3_elimination/training
This reaction matched rate rule [NHDNNH2]
family: 1,3_NH3_elimination
""",
)

entry(
    index = 21,
    label = "NNHJ + NH2(D) <=> N2 + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(920000,'cm^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 82 H2N + HN2 <=> H3N + N2 in Disproportionation/training
    This reaction matched rate rule [NH2_rad;N3d/H_d_Nrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 82 H2N + HN2 <=> H3N + N2 in Disproportionation/training
This reaction matched rate rule [NH2_rad;N3d/H_d_Nrad]
family: Disproportionation
""",
)

entry(
    index = 22,
    label = "H2 + NH2(D) <=> H + NH3",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(20300,'cm^3/(mol*s)'), n=2.58163, Ea=(6538,'cal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 67 NH2_r3 + H2 <=> NH3_p23 + H_p in H_Abstraction/training
    This reaction matched rate rule [NH3;H_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 67 NH2_r3 + H2 <=> NH3_p23 + H_p in H_Abstraction/training
This reaction matched rate rule [NH3;H_rad]
family: H_Abstraction
""",
)

entry(
    index = 23,
    label = "NH2(D) + H2NN(T) <=> NNHJ + NH3",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.6e+06,'cm^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 89 H2N + H2N2 <=> H3N + HN2 in Disproportionation/training
    This reaction matched rate rule [NH2_rad;N3s/H2_s_Nbirad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 89 H2N + H2N2 <=> H3N + HN2 in Disproportionation/training
This reaction matched rate rule [NH2_rad;N3s/H2_s_Nbirad]
family: Disproportionation
""",
)

entry(
    index = 24,
    label = "NH2(D) + HNNH <=> NNHJ + NH3",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.6e+06,'cm^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Matched reaction 639 NH2_r3 + H2N2 <=> NH3_p23 + HN2 in H_Abstraction/training
    This reaction matched rate rule [NH3;N3d_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 639 NH2_r3 + H2N2 <=> NH3_p23 + HN2 in H_Abstraction/training
This reaction matched rate rule [NH3;N3d_rad]
family: H_Abstraction
""",
)

entry(
    index = 25,
    label = "NH2(D) + N2H2(T) <=> NNHJ + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using an average for rate rule [NH2_rad;NH_s_Rbirad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [NH2_rad;NH_s_Rbirad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 26,
    label = "NH2(D) + NNH2(S) <=> NNHJ + NH3",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.84e+06,'cm^3/(mol*s)'), n=1.94, Ea=(3.64008,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 3077 used for N5dc_H;NH2_rad
    Exact match found for rate rule [N5dc_H;NH2_rad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 3077 used for N5dc_H;NH2_rad
Exact match found for rate rule [N5dc_H;NH2_rad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 27,
    label = "X + NN[Pt] <=> H_X + NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(202.485,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 28,
    label = "N_X + NN[Pt] <=> NH_X + NN=[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 29,
    label = "N_X + NN[Pt] <=> NH_X + NN=[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 30,
    label = "X + H3N4X <=> NNHJX + NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(40.2418,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 31,
    label = "X + NN(N=N)[Pt] <=> [Pt]N=N + NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(158.912,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 32,
    label = "NH_X + NN[Pt] <=> NH2_X + NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-H]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 33,
    label = "X + NN([Pt])N <=> NH2_X + NN=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+17,'m^2/(mol*s)'), n=0, Ea=(180.897,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 34,
    label = "N_X + NN([Pt])N <=> NN=[Pt] + NN=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 35,
    label = "N2 + N2(T) <=> 1_N4(T)",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1.11891e+20,'m^3/(mol*s)'), n=-4.51667, Ea=(52.89,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N3t_N3t;YJ] for rate rule [N3t_N3t;N3dJ]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [N3t_N3t;YJ] for rate rule [N3t_N3t;N3dJ]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 36,
    label = "N2(T) + N2(T) <=> 1_N4(T)",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(812248,'m^3/(mol*s)'), n=0.906369, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.153305029067, var=35.949358839, Tref=1000.0, N=8, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R
        Total Standard Deviation in ln(k): 12.4051358263
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R
    Total Standard Deviation in ln(k): 12.4051358263
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 37,
    label = "H + [N]NN=[N] <=> 1_N4(T) + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.8e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using an average for rate rule [H_rad;N3H_s_Rbirad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [H_rad;N3H_s_Rbirad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 38,
    label = "H + 7_N4H <=> 1_N4(T) + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.8e+08,'cm^3/(mol*s)'), n=1.5, Ea=(6.61072,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 636 used for N3d/H/NonDeN;H_rad
    Exact match found for rate rule [N3d/H/NonDeN;H_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 636 used for N3d/H/NonDeN;H_rad
Exact match found for rate rule [N3d/H/NonDeN;H_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 39,
    label = "H + [NH][N]N=[N] <=> 1_N4(T) + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.8e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using an average for rate rule [H_rad;NH_s_Rbirad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [H_rad;NH_s_Rbirad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 40,
    label = "H + HN4 <=> 1_N4(T) + H2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(17.4054,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 3073 used for N5dc_H;H_rad
    Exact match found for rate rule [N5dc_H;H_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 3073 used for N5dc_H;H_rad
Exact match found for rate rule [N5dc_H;H_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 41,
    label = "N2 + 1_N4(T) <=> [N]=NN=NN=[N]",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(0.002456,'m^3/(mol*s)'), n=2.756, Ea=(234.155,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R_R;N3J] for rate rule [N3t_N3t;N3dJ_N]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 4.0
    family: R_Addition_MultipleBond
    Ea raised from 231.7 to 234.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [R_R;N3J] for rate rule [N3t_N3t;N3dJ_N]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 4.0
family: R_Addition_MultipleBond
Ea raised from 231.7 to 234.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 42,
    label = "N2 + 1_N4(T) <=> N6",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1.11891e+20,'m^3/(mol*s)'), n=-4.51667, Ea=(52.89,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N3t_N3t;YJ] for rate rule [N3t_N3t;NJ]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [N3t_N3t;YJ] for rate rule [N3t_N3t;NJ]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 43,
    label = "X + X + 1_N4(T) <=> [Pt]N=[N] + [Pt]N=[N]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(448.058,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 44,
    label = "X + 1_N4(T) <=> [Pt]N=NN=[N]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 45,
    label = "X + 1_N4(T) <=> [N]=NN=[N].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(26.9902,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW
    Ea raised from 0.0 to 27.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 27.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 46,
    label = "X + 1_N4(T) <=> N4X",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.2, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 47,
    label = "1_N4(T) + H <=> 7_N4H",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.64895e+13,'m^3/(mol*s)'), n=-1.49865, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.381367412635, var=9.46235787476, Tref=1000.0, N=7, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
        Total Standard Deviation in ln(k): 7.12496428854
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
    Total Standard Deviation in ln(k): 7.12496428854
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 48,
    label = "1_N4(T) + H <=> HN4",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.64895e+13,'m^3/(mol*s)'), n=-1.49865, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.381367412635, var=9.46235787476, Tref=1000.0, N=7, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
        Total Standard Deviation in ln(k): 7.12496428854
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO
    Total Standard Deviation in ln(k): 7.12496428854
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 49,
    label = "1_N4(T) + H <=> [N]NN=[N]",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.982e+35,'cm^3/(mol*s)'), n=-7.67, Ea=(52.551,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Estimated using an average for rate rule [N3d_Nd;HJ]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using an average for rate rule [N3d_Nd;HJ]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 50,
    label = "1_N4(T) + H <=> [N]NN=[N]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(9.89174e+09,'m^3/(mol*s)'), n=-1.15717, Ea=(21.4703,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R_R;HJ]
    Euclidian distance = 0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using an average for rate rule [R_R;HJ]
Euclidian distance = 0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 51,
    label = "1_N4(T) + H <=> [NH][N]N=[N]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.97699e+30,'m^3/(mol*s)'), n=-8.04, Ea=(52.3,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Nd_R;HJ] for rate rule [N1dc_R;HJ]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [Nd_R;HJ] for rate rule [N1dc_R;HJ]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 52,
    label = "1_N4(T) + NNHJ <=> N2 + 7_N4H",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.4e+06,'cm^3/(mol*s)'), n=2, Ea=(-4.97896,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [N3d_rad;N3d/H_d_Nrad] for rate rule [N3d_rad/N;N3d/H_d_Nrad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [N3d_rad;N3d/H_d_Nrad] for rate rule [N3d_rad/N;N3d/H_d_Nrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 53,
    label = "N2(T) + [N]NN=[N] <=> 1_N4(T) + NNHJ",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.6,'m^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N3_rad;N3H_s_Rbirad] for rate rule [N3d_rad;N3H_s_Rbirad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [N3_rad;N3H_s_Rbirad] for rate rule [N3d_rad;N3H_s_Rbirad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 54,
    label = "1_N4(T) + NNHJ <=> N=NN=NN=[N]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.06248e+31,'m^3/(mol*s)'), n=-7.48856, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.354218852058, var=34.8187486739, Tref=1000.0, N=6, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
        Total Standard Deviation in ln(k): 12.7194203157
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
    Total Standard Deviation in ln(k): 12.7194203157
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 55,
    label = "1_N4(T) + NNHJ <=> N2 + HN4",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(6.3946,'m^3/(mol*s)'), n=1.93833, Ea=(-4.81857,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;N3d/H_d_Nrad] for rate rule [N5_rad;N3d/H_d_Nrad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;N3d/H_d_Nrad] for rate rule [N5_rad;N3d/H_d_Nrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 56,
    label = "N2(T) + [NH][N]N=[N] <=> 1_N4(T) + NNHJ",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.6,'m^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [N3_rad;NH_s_Rbirad] for rate rule [N3d_rad;NH_s_Rbirad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [N3_rad;NH_s_Rbirad] for rate rule [N3d_rad;NH_s_Rbirad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 57,
    label = "1_N4(T) + NNHJ <=> HN6",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.8583e+07,'m^3/(mol*s)'), n=-0.3, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=4.40309720458e-11, var=16.7795781874, Tref=1000.0, N=3, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
        Total Standard Deviation in ln(k): 8.21197292804
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
    Total Standard Deviation in ln(k): 8.21197292804
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 58,
    label = "1_N4(T) + NNHJ <=> HN6-2",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(0.001228,'m^3/(mol*s)'), n=2.756, Ea=(106.921,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R_R;N3J] for rate rule [N3d_Nd;N3dJ_N]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond
    Ea raised from 100.7 to 106.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [R_R;N3J] for rate rule [N3d_Nd;N3dJ_N]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
Ea raised from 100.7 to 106.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 59,
    label = "1_N4(T) + NNHJ <=> HN6-2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(0.000614,'m^3/(mol*s)'), n=2.756, Ea=(106.921,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R_R;N3J] for rate rule [R_R;N3dJ_N]
    Euclidian distance = 2.0
    family: R_Addition_MultipleBond
    Ea raised from 100.7 to 106.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [R_R;N3J] for rate rule [R_R;N3dJ_N]
Euclidian distance = 2.0
family: R_Addition_MultipleBond
Ea raised from 100.7 to 106.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 60,
    label = "1_N4(T) + NNHJ <=> N=N[N]N=N[N]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.001228,'m^3/(mol*s)'), n=2.756, Ea=(6.93707,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R_R;N3J] for rate rule [N1dc_R;N3dJ_N]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [R_R;N3J] for rate rule [N1dc_R;N3dJ_N]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 61,
    label = "N2(T) + 7_N4H <=> 1_N4(T) + NNHJ",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(28.1425,'m^3/(mol*s)'), n=1.75, Ea=(8.14417,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [N3d/H/NonDeN;Y_1centerbirad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [N3d/H/NonDeN;Y_1centerbirad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 62,
    label = "1_N4(T) + NNHJ <=> HN6-3",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.06248e+31,'m^3/(mol*s)'), n=-7.48856, Ea=(0.106911,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.354218852058, var=34.8187486739, Tref=1000.0, N=6, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
        Total Standard Deviation in ln(k): 12.7194203157
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0
    Total Standard Deviation in ln(k): 12.7194203157
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 63,
    label = "N2(T) + HN4 <=> 1_N4(T) + NNHJ",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.7e+08,'cm^3/(mol*s)'), n=1.5, Ea=(9.87424,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [N5dc_H;Y_1centerbirad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [N5dc_H;Y_1centerbirad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 64,
    label = "1_N4(T) + NNHJ <=> HN6-4",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.8583e+07,'m^3/(mol*s)'), n=-0.3, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=4.40309720458e-11, var=16.7795781874, Tref=1000.0, N=3, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
        Total Standard Deviation in ln(k): 8.21197292804
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
    Total Standard Deviation in ln(k): 8.21197292804
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 65,
    label = "[N]NN=[N] + NH2(D) <=> 1_N4(T) + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using an average for rate rule [NH2_rad;N3H_s_Rbirad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [NH2_rad;N3H_s_Rbirad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 66,
    label = "7_N4H + NH2(D) <=> 1_N4(T) + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 639 used for N3d/H/NonDeN;NH2_rad
    Exact match found for rate rule [N3d/H/NonDeN;NH2_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 639 used for N3d/H/NonDeN;NH2_rad
Exact match found for rate rule [N3d/H/NonDeN;NH2_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 67,
    label = "[NH][N]N=[N] + NH2(D) <=> 1_N4(T) + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)'), n=1.94, Ea=(-4.8116,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using an average for rate rule [NH2_rad;NH_s_Rbirad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [NH2_rad;NH_s_Rbirad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 68,
    label = "HN4 + NH2(D) <=> 1_N4(T) + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(920000,'cm^3/(mol*s)'), n=1.94, Ea=(3.64008,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 3077 used for N5dc_H;NH2_rad
    Exact match found for rate rule [N5dc_H;NH2_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 3077 used for N5dc_H;NH2_rad
Exact match found for rate rule [N5dc_H;NH2_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 69,
    label = "H3N5 <=> 1_N4(T) + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.20327e+09,'s^-1'), n=1.83, Ea=(106.975,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NNHNH2]
    Euclidian distance = 0
    family: 1,2_NH3_elimination"""),
    longDesc = 
"""
Estimated using an average for rate rule [NNHNH2]
Euclidian distance = 0
family: 1,2_NH3_elimination
""",
)

entry(
    index = 70,
    label = "NNN=N[N] <=> 1_N4(T) + NH3",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.13e+08,'s^-1'), n=1.68, Ea=(171.3,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(3000,'K'), comment="""From training reaction 4 used for non_charged
    Exact match found for rate rule [non_charged]
    Euclidian distance = 0
    family: 1,2_NH3_elimination"""),
    longDesc = 
"""
From training reaction 4 used for non_charged
Exact match found for rate rule [non_charged]
Euclidian distance = 0
family: 1,2_NH3_elimination
""",
)

entry(
    index = 71,
    label = "1_N4(T) + 1_N4(T) <=> N8",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(3.7166e+07,'m^3/(mol*s)'), n=-0.3, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=4.40309720458e-11, var=16.7795781874, Tref=1000.0, N=3, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
        Total Standard Deviation in ln(k): 8.21197292804
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
    Total Standard Deviation in ln(k): 8.21197292804
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: R_Recombination
""",
)

entry(
    index = 72,
    label = "1_N4(T) + 1_N4(T) <=> N8-2",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.8583e+07,'m^3/(mol*s)'), n=-0.3, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=4.40309720458e-11, var=16.7795781874, Tref=1000.0, N=3, correlation='Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
        Total Standard Deviation in ln(k): 8.21197292804
    Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C
    Total Standard Deviation in ln(k): 8.21197292804
Exact match found for rate rule [Root_N-1R->H_1CNOS->N_Ext-2R-R_3R!H-u0_N-2R->C_N-3R!H->C]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 73,
    label = "X + [Pt]NN=N <=> H_X + N=NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(117.789,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 74,
    label = "N_X + [Pt]NN=N <=> NH_X + N=NN=[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 75,
    label = "N_X + [Pt]NN=N <=> NH_X + N=NN=[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 76,
    label = "N2X + [Pt]NN=N <=> NNHJX + N=NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-H]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 77,
    label = "X + H2N5X <=> NNHJX + N=NN=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 78,
    label = "X + N=NN(N=N)[Pt] <=> [Pt]N=N + N=NN=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+17,'m^2/(mol*s)'), n=0, Ea=(76.4983,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 79,
    label = "NH_X + [Pt]NN=N <=> N=NN=[Pt] + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-H]
    Euclidian distance = 0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 80,
    label = "X + NN(N=N)[Pt] <=> N=NN=[Pt] + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(88.3879,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 81,
    label = "N_X + NN(N=N)[Pt] <=> N=NN=[Pt] + NN=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 82,
    label = "N_X + N=NN(N=N)[Pt] <=> N=NN=[Pt] + N=NN=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;Donating]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;Donating]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

