#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + H2 <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 1,
    label = "X + N2 <=> N#N.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 2,
    label = "X + X + H2 <=> H_X + H_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=4.007e-07, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Ammonia_Ru
""",
)

entry(
    index = 3,
    label = "X + X + N2 <=> N_X + N_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=2.892e-10, n=0, Ea=(38.949,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Ammonia_Ru
""",
)

entry(
    index = 4,
    label = "H + H <=> H2",
    degeneracy = 0.5,
    duplicate = True,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 5,
    label = "X + H <=> H_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 6,
    label = "H + H <=> H2",
    degeneracy = 0.5,
    duplicate = True,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 7,
    label = "H + NNHJ <=> N2 + H2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(2.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
    This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
family: Disproportionation
""",
)

entry(
    index = 8,
    label = "N2 + H <=> NNHJ",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.6e+15,'cm^3/(mol*s)'), n=-0.64, Ea=(15333,'cal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(25000,'K'), comment="""Matched reaction 185 N2 + H <=> NNH in R_Addition_MultipleBond/training
    This reaction matched rate rule [N3t_N3t;HJ]
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Matched reaction 185 N2 + H <=> NNH in R_Addition_MultipleBond/training
This reaction matched rate rule [N3t_N3t;HJ]
family: R_Addition_MultipleBond
""",
)

entry(
    index = 9,
    label = "H + NNHJ <=> N2 + H2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(2.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
    This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
    family: Disproportionation"""),
    longDesc = 
"""
Matched reaction 79 H + HN2 <=> H2 + N2 in Disproportionation/training
This reaction matched rate rule [H_rad;N3d/H_d_Nrad]
family: Disproportionation
""",
)

entry(
    index = 10,
    label = "N_X + H_X <=> X + NH_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.424e+16,'m^2/(mol*s)'), n=0, Ea=(77.62,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Ammonia_Ru
""",
)

entry(
    index = 11,
    label = "X + NNHJ <=> NNHJX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 12,
    label = "X + NNHJ <=> [Pt]N=N",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 13,
    label = "H_X + NH_X <=> X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.949e+15,'m^2/(mol*s)'), n=0.083, Ea=(75.236,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Ammonia_Ru
""",
)

entry(
    index = 14,
    label = "N_X + NH2_X <=> NH_X + NH_X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1e+18,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Abstracting;R-H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 15,
    label = "X + X + NH3 <=> H_X + NH2_X",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(A=0.03, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 16,
    label = "X + NN=[Pt] <=> N_X + NH2_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(200.6,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 17,
    label = "1_N4(T) <=> N2 + N2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(5e+12,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule [RJJ]
    Euclidian distance = 0
    family: 1,4_Linear_birad_scission"""),
    longDesc = 
"""
Exact match found for rate rule [RJJ]
Euclidian distance = 0
family: 1,4_Linear_birad_scission
""",
)

entry(
    index = 18,
    label = "1_N4(T) <=> N2 + N2",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(5e+12,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule [RJJ]
    Euclidian distance = 0
    family: 1,4_Linear_birad_scission"""),
    longDesc = 
"""
Exact match found for rate rule [RJJ]
Euclidian distance = 0
family: 1,4_Linear_birad_scission
""",
)

entry(
    index = 19,
    label = "X + NH3 <=> NH3_X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1.247e-09, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Ammonia_Ru
""",
)

entry(
    index = 20,
    label = "H_X + NH2_X <=> X + NH3_X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.886e+15,'m^2/(mol*s)'), n=0.083, Ea=(17.036,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Ammonia_Ru
""",
)

entry(
    index = 21,
    label = "X + NNHJ <=> NNHJX-2",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(26.4446,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW
    Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 22,
    label = "X + N=NN=[Pt] <=> N_X + [Pt]N=N",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(271.124,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

